### ISSUE TITLE
Getting FileNotFoundException Error while submitting workload 

### ISSUE THREAD

**Issue by gowthamshankar99** [sample-accelerators/steeltoe-weatherforecast#9]
Workload submission is failing with the following error 

This error was extracted from the logs of the Deployment pod spun up after the supply chain is completed.

```
Message:    Setting ASPNETCORE_URLS=http://0.0.0.0:8080/
Unhandled exception. System.IO.DirectoryNotFoundException: /workspace/StaticFiles/
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Program.<Main>$(String[] args) in /workspace/Program.cs:line 34
```

**Comment by trisberg** [comment]
The config/workload.yaml points to the main branch so if you deploy using that workload file then the latest change to use dotnet 6 will cause this error - https://github.com/sample-accelerators/steeltoe-weatherforecast/blob/main/config/workload.yaml#L8-L13

Generating the accelerator code and pushing what is generated to a different Git repo or using the local source to build should still work. Try using (this is in the README):

```
tanzu apps workload create sample-app -f config/workload.yaml \
  --local-path . \
  --source-image <REPOSITORY-PREFIX>/sample-app-source \
  --type web
```
